const ESSENTIAL_SESSIONS = [
  {
    id: 1,
    title: "Upper body 1",
    date: "",
    exercices: [
      {
        name: "dips",
        warm_up: 2,
        sets: [
          {
            set: 1,
            rep: "4-6",
            rep_value: "",
            load: "10",
            load_value: "",
            rpe: "8-9",
            rpe_value: "",
            rest: 3,
          },
        ],
      },
      {
        name: "dips",
        warm_up: 0,
        sets: [
          {
            set: 1,
            rep: "8-10",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 3,
          },
        ],
      },
      {
        name: "2 Grip Pull-up",
        warm_up: 2,
        sets: [
          {
            set: 1,
            rep: "10-12",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 2,
          },
          {
            set: 2,
            rep: "10-12",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 2,
          },
        ],
      },
      {
        name: "Seated DB Shouder Press",
        warm_up: 1,
        sets: [
          {
            set: 1,
            rep: "10-12",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 2,
          },
          {
            set: 2,
            rep: "10-12",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 2,
          },
        ],
      },
      {
        name: "Seated Cable Row",
        warm_up: 1,
        sets: [
          {
            set: 1,
            rep: "10-12(dropset)",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 2,
          },
          {
            set: 2,
            rep: "10-12(dropset)",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "9-10",
            rpe_value: "",
            rest: 2,
          },
        ],
      },
      {
        name: "EZ Bar Skull Cruhser",
        warm_up: 1,
        sets: [
          {
            set: 1,
            rep: "12-15",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "10",
            rpe_value: "",
            rest: 0,
          },
          {
            set: 2,
            rep: "12-15",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "10",
            rpe_value: "",
            rest: 0,
          },
        ],
      },
      {
        name: "EZ Bar Curl",
        warm_up: 1,
        sets: [
          {
            set: 1,
            rep: "12-15",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "10",
            rpe_value: "",
            rest: 1.5,
          },
          {
            set: 2,
            rep: "12-15",
            rep_value: "",
            load: "0",
            load_value: "",
            rpe: "10",
            rpe_value: "",
            rest: 1.5,
          },
        ],
      },
    ],
  },
];

export default ESSENTIAL_SESSIONS;
